import fs from "fs";
import path from "path";

const INDEX_FILENAME = ".hackathon-index.md";
const IGNORE_DIRS = new Set(["node_modules", ".git", "dist", ".next", "out", "coverage", ".cache"]);
const MAX_DEPTH = 4;

interface FileEntry {
  relPath: string;
  type: "file" | "dir";
}

function scanDir(dir: string, root: string, depth: number): FileEntry[] {
  if (depth > MAX_DEPTH) return [];
  const entries: FileEntry[] = [];
  let items: fs.Dirent[];
  try {
    items = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return [];
  }
  for (const item of items) {
    if (item.name.startsWith(".") && item.name !== ".env.example") continue;
    if (IGNORE_DIRS.has(item.name)) continue;
    const full = path.join(dir, item.name);
    const rel = path.relative(root, full);
    if (item.isDirectory()) {
      entries.push({ relPath: rel, type: "dir" });
      entries.push(...scanDir(full, root, depth + 1));
    } else {
      entries.push({ relPath: rel, type: "file" });
    }
  }
  return entries;
}

function buildMarkdown(dir: string, entries: FileEntry[]): string {
  const now = new Date().toISOString();
  const lines: string[] = [
    `# Hackathon Index – ${path.basename(dir)}`,
    `> Auto-generated by hackathon-mode on ${now}`,
    "",
    "## Structure",
    "```",
  ];
  for (const e of entries) {
    const segments = e.relPath.split(path.sep);
    const depth = segments.length - 1;
    const indent = "  ".repeat(depth);
    const label = segments[segments.length - 1];
    const icon = e.type === "dir" ? "📁" : "📄";
    lines.push(`${indent}${icon} ${label}`);
  }
  lines.push("```", "", "## Key Files");
  const keyExts = new Set([".ts", ".tsx", ".js", ".jsx", ".py", ".go", ".rs", ".json", ".yaml", ".yml", ".md", ".env.example"]);
  const keyFiles = entries.filter((e) => e.type === "file" && keyExts.has(path.extname(e.relPath)));
  for (const f of keyFiles) {
    lines.push(`- [${f.relPath}](./${f.relPath})`);
  }
  lines.push("", "_Use this file to orient yourself quickly in a new agent turn._");
  return lines.join("\n");
}

export function updateIndex(workspaceRoot: string): string {
  const entries = scanDir(workspaceRoot, workspaceRoot, 0);
  const content = buildMarkdown(workspaceRoot, entries);
  const indexPath = path.join(workspaceRoot, INDEX_FILENAME);
  fs.writeFileSync(indexPath, content, "utf-8");
  return indexPath;
}

export function readIndex(workspaceRoot: string): string | null {
  const indexPath = path.join(workspaceRoot, INDEX_FILENAME);
  try {
    return fs.readFileSync(indexPath, "utf-8");
  } catch {
    return null;
  }
}

export function getFileTree(workspaceRoot: string, maxDepth = 3): string {
  const entries = scanDir(workspaceRoot, workspaceRoot, 0).filter(
    (e) => e.relPath.split(path.sep).length <= maxDepth
  );
  return entries.map((e) => (e.type === "dir" ? `[dir] ${e.relPath}` : `[file] ${e.relPath}`)).join("\n");
}
